namespace SpriteKind {
    export const tower = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    BULLET_SPEED = 100
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet2 = sprites.createProjectileFromSprite(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet2.setScale(0.6, ScaleAnchor.Middle)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    BULLET_SPEED = 100
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet1 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . 2 2 1 1 1 1 2 . . 
        . . . . 2 2 3 3 1 1 1 1 1 1 . . 
        . . 3 3 3 3 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 3 3 2 2 3 1 1 1 1 1 1 1 . . 
        . . . . . . 2 2 3 1 1 1 1 2 . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet1.rotation = theta
})
let enemy1: Sprite = null
let ENEMY_SPEED = 0
let bullet1: Sprite = null
let bullet2: Sprite = null
let theta = 0
let dy = 0
let dx = 0
let BULLET_SPEED = 0
let artillery: Sprite = null
let target: Sprite = null
target = sprites.create(assets.image`myImage`, SpriteKind.Player)
controller.moveSprite(target)
target.setStayInScreen(true)
let tower = sprites.create(assets.image`myImage2`, SpriteKind.tower)
tower.setScale(0.6, ScaleAnchor.Middle)
tower.y = 115
artillery = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........beeeeeeb........
    .......beeeeeeeeb.......
    ......beeeeeeeeeeb......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......ce77eeee67ee......
    ...668ce7768867788666...
    ..6776ee77777777667776..
    ...6776666eeee6766776...
    ....6776eeeeeeeee676....
    .....6eeeeeeeeeece6.....
    ......eeeeeeeeeece......
    ......eeeeeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeece......
    ......eefeeeeeeece......
    ......ee6eeeeee6ce......
    ......ee77eeee67ee......
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ......feeeeeeeeeefe.....
    ......eeeeeeeeeeeff.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeeef.....
    ......eeeeeeeeeeeef.....
    ......ee6eeeeee6cef.....
    ......ee77eeee67eeee....
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.tower)
artillery.y = 115
artillery.setScale(0.6, ScaleAnchor.Middle)
forever(function () {
    ENEMY_SPEED = 10
    enemy1 = sprites.create(assets.image`myImage0`, SpriteKind.Enemy)
    enemy1.setPosition(randint(10, 150), 0)
    dx = tower.x - enemy1.x
    dy = 110
    theta = Math.atan2(dy, dx)
    enemy1.setVelocity(ENEMY_SPEED * Math.cos(theta), ENEMY_SPEED * Math.sin(theta))
    pause(randint(500, 3000))
})
