namespace SpriteKind {
    export const tower = SpriteKind.create()
    export const tower_kind = SpriteKind.create()
}
/**
 * デバッグまだ
 */
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    sprites.changeDataNumberBy(otherSprite, "hp", -5)
    statusbars.getStatusBarAttachedTo(StatusBarKind.Health, otherSprite).value = sprites.readDataNumber(otherSprite, "hp")
    if (sprites.readDataNumber(otherSprite, "hp") <= 0) {
        sprites.destroy(otherSprite, effects.fire, 100)
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    BULLET_SPEED = 100
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet2 = sprites.createProjectileFromSprite(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet2.setScale(0.6, ScaleAnchor.Middle)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.tower_kind, function (sprite2, otherSprite2) {
    sprite2.setVelocity(0, 0)
    while (true) {
        tower_hp += -5
        tower_statusbar.value = tower_hp
        otherSprite2.sayText(sprites.readDataNumber(otherSprite2, "hp"), 500, false)
        pause(1000)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.InBackground)
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet1 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . 2 2 1 1 1 1 2 . . 
        . . . . 2 2 3 3 1 1 1 1 1 1 . . 
        . . 3 3 3 3 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 3 3 2 2 3 1 1 1 1 1 1 1 . . 
        . . . . . . 2 2 3 1 1 1 1 2 . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet1.rotation = theta
})
function init () {
    ENEMY1_HP = 10
    ENEMY1_SPEED = 10
    ENEMY2_HP = 30
    ENEMY2_SPEED = 10
    ENEMY2_AMP = 15
    ENEMY2_T = 1000
    BULLET_SPEED = 100
    TOWER_MAXHP = 500
}
function enemy1_appear () {
    enemy1 = sprites.create(assets.image`myImage0`, SpriteKind.Enemy)
    animation.runImageAnimation(
    enemy1,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    true
    )
    x0 = 0
    y0 = 0
    enemy_theta(enemy1, ENEMY1_HP, x0, y0)
    sprites.setDataNumber(enemy1, "hp", ENEMY1_HP)
    sprites.setDataNumber(enemy1, "theta", theta)
    sprites.setDataNumber(enemy1, "spawn_time", game.runtime())
    sprites.setDataNumber(enemy1, "x0", x0)
    sprites.setDataNumber(enemy1, "y0", y0)
    enemy1.setVelocity(ENEMY1_SPEED * Math.cos(theta), ENEMY1_SPEED * Math.sin(theta))
    enemy_statusbar = statusbars.create(20, 2, StatusBarKind.Health)
    enemy_statusbar.max = sprites.readDataNumber(enemy1, "hp")
    enemy_statusbar.attachToSprite(enemy1)
}
function enemy2_appear () {
    enemy2 = sprites.create(assets.image`myImage0`, SpriteKind.Enemy)
    animation.runImageAnimation(
    enemy2,
    [img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c b b b b b b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b c b b b c b b b b f . . . . 
        f b 1 f f f 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . f f f . . . . . . . . . . . 
        f f f c c . . . . . . . . f f f 
        f f c c . . c c . . . f c b b c 
        f f c 3 c c 3 c c f f b b b c . 
        f f b 3 b c 3 b c f b b c c c . 
        . c b b b b b b c f b c b c c . 
        . c b b b b b b c b b c b b c . 
        c b 1 b b b 1 b b b c c c b c . 
        c b b b b b b b b c c c c c . . 
        f b c b b b c b b b b f c . . . 
        f b 1 f f f 1 b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . c c . . c c . . . . . . . . 
        . . c 3 c c 3 c c c . . . . . . 
        . c b 3 b c 3 b c c c . . . . . 
        . c b b b b b b b b f f . . . . 
        c c b b b b b b b b f f . . . . 
        c b 1 b b b 1 b b c f f f . . . 
        c b b b b b b b b f f f f . . . 
        f b c b b b c b c c b b b . . . 
        f b 1 f f f 1 b f c c c c . . . 
        . f b b b b b b f b b c c . . . 
        c c f b b b b b c c b b c . . . 
        c c c f f f f f f c c b b c . . 
        . c c c . . . . . . c c c c c . 
        . . c c c . . . . . . . c c c c 
        . . . . . . . . . . . . . . . . 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c b 1 b b b 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `],
    200,
    true
    )
    x0 = 0
    y0 = 0
    enemy_theta(enemy2, ENEMY2_HP, x0, y0)
    sprites.setDataNumber(enemy2, "hp", ENEMY2_HP)
    sprites.setDataNumber(enemy2, "theta", theta)
    sprites.setDataNumber(enemy2, "spawn_time", game.runtime())
    sprites.setDataNumber(enemy2, "x0", x0)
    sprites.setDataNumber(enemy2, "y0", y0)
    enemy2_list.push(enemy2)
    enemy2.setVelocity(ENEMY2_SPEED * Math.cos(theta), ENEMY2_SPEED * Math.sin(theta))
    enemy_statusbar = statusbars.create(20, 2, StatusBarKind.Health)
    enemy_statusbar.max = sprites.readDataNumber(enemy2, "hp")
    enemy_statusbar.attachToSprite(enemy2)
}
function enemy_theta (mySprite: Sprite, hp: number, x: number, y: number) {
    mySprite.setPosition(x, y)
    dx = tower2.x - mySprite.x
    dy = 110
    theta = Math.atan2(dy, dx)
}
let sinA = 0
let cosA = 0
let wave = 0
let rad = 0
let dist = 0
let t = 0
let enemy2: Sprite = null
let enemy_statusbar: StatusBarSprite = null
let y0 = 0
let x0 = 0
let enemy1: Sprite = null
let ENEMY2_T = 0
let ENEMY2_AMP = 0
let ENEMY2_SPEED = 0
let ENEMY2_HP = 0
let ENEMY1_SPEED = 0
let ENEMY1_HP = 0
let bullet1: Sprite = null
let bullet2: Sprite = null
let theta = 0
let dy = 0
let dx = 0
let BULLET_SPEED = 0
let artillery: Sprite = null
let tower_statusbar: StatusBarSprite = null
let TOWER_MAXHP = 0
let tower_hp = 0
let tower2: Sprite = null
let target: Sprite = null
let enemy2_list: Sprite[] = []
init()
enemy2_list = []
target = sprites.create(assets.image`myImage`, SpriteKind.Player)
controller.moveSprite(target)
target.setStayInScreen(true)
tower2 = sprites.create(assets.image`myImage2`, SpriteKind.tower_kind)
tower2.setScale(0.6, ScaleAnchor.Middle)
tower2.y = 115
tower_hp = TOWER_MAXHP
tower_statusbar = statusbars.create(50, 4, StatusBarKind.Health)
tower_statusbar.max = tower_hp
tower_statusbar.value = tower_hp
tower2.sayText(sprites.readDataNumber(tower2, "hp"))
tower_statusbar.attachToSprite(tower2, -10, 40)
artillery = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........beeeeeeb........
    .......beeeeeeeeb.......
    ......beeeeeeeeeeb......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......ce77eeee67ee......
    ...668ce7768867788666...
    ..6776ee77777777667776..
    ...6776666eeee6766776...
    ....6776eeeeeeeee676....
    .....6eeeeeeeeeece6.....
    ......eeeeeeeeeece......
    ......eeeeeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeece......
    ......eefeeeeeeece......
    ......ee6eeeeee6ce......
    ......ee77eeee67ee......
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ......feeeeeeeeeefe.....
    ......eeeeeeeeeeeff.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeeef.....
    ......eeeeeeeeeeeef.....
    ......ee6eeeeee6cef.....
    ......ee77eeee67eeee....
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.tower_kind)
artillery.setScale(0.6, ScaleAnchor.Middle)
artillery.y = 115
game.onUpdate(function () {
    for (let i of enemy2_list) {
        t = game.runtime() - sprites.readDataNumber(i, "spawn_time")
        theta = sprites.readDataNumber(i, "theta")
        dist = t / 20 * ENEMY2_SPEED
        rad = t % ENEMY2_T / ENEMY2_T * Math.PI * 2
        wave = Math.sin(rad) * ENEMY2_AMP
        cosA = Math.cos(theta)
        sinA = Math.sin(theta)
        i.setPosition(sprites.readDataNumber(i, "x0") + dist * cosA + wave * (sinA * -1), sprites.readDataNumber(i, "y0") + dist * sinA + wave * (cosA * -1))
    }
})
forever(function () {
    enemy2_appear()
    pause(5000)
})
