namespace SpriteKind {
    export const tower = SpriteKind.create()
    export const tower_kind = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    enemy_statusbar.value = sprites.readDataNumber(otherSprite, "hp")
    sprites.changeDataNumberBy(otherSprite, "hp", -5)
    enemy_statusbar.value = sprites.readDataNumber(otherSprite, "hp")
    otherSprite.sayText(sprites.readDataNumber(otherSprite, "hp"))
    if (sprites.readDataNumber(otherSprite, "hp") <= 0) {
        sprites.destroy(otherSprite, effects.fire, 100)
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    BULLET_SPEED = 100
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet2 = sprites.createProjectileFromSprite(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet2.setScale(0.6, ScaleAnchor.Middle)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    dx = target.x - artillery.x
    dy = target.y - artillery.y
    theta = Math.atan2(dy, dx)
    bullet1 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . 2 2 1 1 1 1 2 . . 
        . . . . 2 2 3 3 1 1 1 1 1 1 . . 
        . . 3 3 3 3 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 3 3 2 2 3 1 1 1 1 1 1 1 . . 
        . . . . . . 2 2 3 1 1 1 1 2 . . 
        . . . . . . . . . 2 2 2 2 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, artillery, BULLET_SPEED * Math.cos(theta), BULLET_SPEED * Math.sin(theta))
    bullet1.rotation = theta
})
function init () {
    ENEMY1_HP = 10
    ENEMY_SPEED = 10
    BULLET_SPEED = 100
    TOWER_MAXHP = 500
}
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.tower_kind, function (sprite, otherSprite) {
    sprite.setVelocity(0, 0)
    while (true) {
        tower_hp += -5
        tower_statusbar.value = tower_hp
        otherSprite.sayText(sprites.readDataNumber(otherSprite, "hp"), 500, false)
        pause(1000)
    }
})
let enemy1: Sprite = null
let ENEMY_SPEED = 0
let ENEMY1_HP = 0
let bullet1: Sprite = null
let bullet2: Sprite = null
let theta = 0
let dy = 0
let dx = 0
let BULLET_SPEED = 0
let enemy_statusbar: StatusBarSprite = null
let artillery: Sprite = null
let tower_statusbar: StatusBarSprite = null
let TOWER_MAXHP = 0
let tower_hp = 0
let target: Sprite = null
init()
target = sprites.create(assets.image`myImage`, SpriteKind.Player)
controller.moveSprite(target)
target.setStayInScreen(true)
let tower2 = sprites.create(assets.image`myImage2`, SpriteKind.tower_kind)
tower2.setScale(0.6, ScaleAnchor.Middle)
tower2.y = 115
tower_hp = TOWER_MAXHP
tower_statusbar = statusbars.create(50, 4, StatusBarKind.Health)
tower_statusbar.max = tower_hp
tower_statusbar.value = tower_hp
tower2.sayText(sprites.readDataNumber(tower2, "hp"))
tower_statusbar.attachToSprite(tower2, -10, 40)
artillery = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........beeeeeeb........
    .......beeeeeeeeb.......
    ......beeeeeeeeeeb......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......ce77eeee67ee......
    ...668ce7768867788666...
    ..6776ee77777777667776..
    ...6776666eeee6766776...
    ....6776eeeeeeeee676....
    .....6eeeeeeeeeece6.....
    ......eeeeeeeeeece......
    ......eeeeeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeefe......
    ......eeceeeeeeece......
    ......eefeeeeeeece......
    ......ee6eeeeee6ce......
    ......ee77eeee67ee......
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ......feeeeeeeeeefe.....
    ......eeeeeeeeeeeff.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeecf.....
    ......eeeeeeeeeeeef.....
    ......eeeeeeeeeeeef.....
    ......ee6eeeeee6cef.....
    ......ee77eeee67eeee....
    ...668ee7768867788666...
    ..6776ee67777777667776..
    ...6777666eeee6667776...
    ....6776eeeeeeeee676....
    .....6feeeeeeeeeef6.....
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.tower_kind)
artillery.setScale(0.6, ScaleAnchor.Middle)
artillery.y = 115
forever(function () {
    enemy1 = sprites.create(assets.image`myImage0`, SpriteKind.Enemy)
    animation.runImageAnimation(
    enemy1,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    true
    )
    sprites.setDataNumber(enemy1, "hp", ENEMY1_HP)
    enemy1.setPosition(randint(10, 150), 0)
    dx = tower2.x - enemy1.x
    dy = 110
    theta = Math.atan2(dy, dx)
    enemy1.setVelocity(ENEMY_SPEED * Math.cos(theta), ENEMY_SPEED * Math.sin(theta))
    enemy_statusbar = statusbars.create(20, 2, StatusBarKind.EnemyHealth)
    enemy_statusbar.max = sprites.readDataNumber(enemy1, "hp")
    enemy_statusbar.attachToSprite(enemy1)
    pause(5000)
})
